FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["HelloWork.Api/HelloWork.Api.csproj", "HelloWork.Api/"]
RUN dotnet restore "HelloWork.Api/HelloWork.Api.csproj"
COPY . .
WORKDIR "/src/HelloWork.Api"
RUN dotnet build "HelloWork.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "HelloWork.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HelloWork.Api.dll"]
